### PR TITLE
perf: Implement node sharing for groupBy

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
Depends on #374

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
- Too much new boilerplate inside collectors. Agree, although it mostly because each collector implement the same class, meaning we need a unique identifier to identify what kind of collector it is. Additionally, since each collector is the same class, we cannot use collector specific fields to identify what kind of collector it is. Third, the collectors construct lambda's using parameters, meaning we cannot rely on their reference equality to check for equals.
- The NodeConstructionFunction is a lambda that uses parameters, meaning we cannot rely on their reference equality to check for equals.
- The user does not need to use our own collectors; they just need to implement equals and hashCode on their custom ConstraintCollector to take advantage of groupBy node sharing

**Comment by triceo** [comment]
May I suggest we leave the `groupBy` node sharing last?

For a while, I've had an idea for a large refactor of the collectors, which will help here. (Main points: remove all of the impls from `ConstraintCollectors` and create a hierarchy of private classes which share code and can put equality where it belongs.)

Wrt. node constructors - maybe the node constructor mechanism has outlived its usefulness and we need a better one. Nobody forces us to use this; it was good for me once, maybe it's not good anymore.

Wrt. user collector equality - indeed, but that needs to be mentioned in the `Uni/Bi...Collector` javadocs.

**Comment by Christopher-Chianelli** [comment]
No problem with me (it being last was my original intention, but I accidentally did the rebasing out-of-order).

**Comment by triceo** [comment]
Ok, let's start here: let's minimize the `ConstraintCollectors` class. At this point, the IDE has a hard time even highlighting things in that class, it's too complex.

- Create impl classes for each kind of collector; not in public API.
- Have subtypes for uni/bi/... Ideally hide constructors or even the entire classes, have a factory static class. (Even if not in public API, the impls would still be on the classpath and therefore visible; people would start using them directly.)
- Equality goes into those classes too.
- `ConstraintCollectors` only exists to create and return instances of those types.

It will be a lot of manual effort, but IMO a very necessary cleanup.
Once we have that, we see what complexity remains to be solved to get us to node sharing.

WDYT?

**Comment by Christopher-Chianelli** [comment]
Sounds good to me; should it be in a separate PR or this one?

**Comment by triceo** [comment]
Separate one is better. `chore`, unrelated to performance.

**Comment by Christopher-Chianelli** [comment]
Superseded by #401

**Pull request closed without merging**
