### PR TITLE
chore: Clean up TODOs after merging nullness markers

### PR DESCRIPTION
**Pull request by triceo**

### CODE REVIEW

**Comment by greyhairredbear** [comment]
Sorry for missing those last todos, thanks for cleaning up - in case my review is sufficient here I can gladly approve

**Comment by triceo** [comment]
@greyhairredbear No worries, I missed them too. :-) I'll leave the review with Fred, since your review wouldn't pass the check to allow me to merge the PR - but feel free to add your comments, if you see something fishy.

**Comment by greyhairredbear** [comment]
> @greyhairredbear No worries, I missed them too. :-) I'll leave the review with Fred, since your review wouldn't pass the check to allow me to merge the PR - but feel free to add your comments, if you see something fishy.

Yeah, thought the approval would need to be by someone with the correct role for this repo. 

PR LGTM, `emptyMatchAnalysisIfNull` looks neat 👍 and I guess `buildScoreCorruptionAnalysis` would only be called in `FULL_ASSERT` mode, so potential performance impacts of allocating new empty lists are negligible, right?

**Comment by triceo** [comment]
> `buildScoreCorruptionAnalysis` would only be called in `FULL_ASSERT` mode, so potential performance impacts of allocating new empty lists are negligible, right?

Correct. And besides, as far as I know, `Collections.emptyList()` doesn't actually create a new instance of anything - it returns a constant.

**Review by zepfred — APPROVED** [review]

**Pull request merged**
