### PR TITLE
feat: Adding the property `nearbyDistanceMeterClass` to `SolverConfig` 

### PR DESCRIPTION
**Pull request by zepfred**
This pull request introduces a new "Nearby" property that will help resolve the CI issue with #673.

### CODE REVIEW

**Comment by zepfred** [comment]
@triceo, the tests are passing locally.

**Comment by triceo** [comment]
Why is this a separate PR? Please integrate this into the original one, as they can't live without one another.

**Review by triceo — CHANGES_REQUESTED** [review]
Why is this a separate PR? Please integrate this into the original one, as they can't live without one another.

**Comment by zepfred** [comment]
> Why is this a separate PR? Please integrate this into the original one, as they can't live without one another.

My main goal was to unblock the tests on the primary PR because they are failing due to:

```
[INFO] --- exec-maven-plugin:3.2.0:exec (check-solver-xsd-changes) @ timefold-solver-core-impl ---
diff --git a/core/core-impl/src/main/resources/solver.xsd b/core/core-impl/src/main/resources/solver.xsd
index aa6680d..76c93b1 100644
--- a/core/core-impl/src/main/resources/solver.xsd
+++ b/core/core-impl/src/main/resources/solver.xsd
@@ -39,6 +39,8 @@
                     
           <xs:element minOccurs="0" name="termination" type="tns:terminationConfig"/>
                     
+          <xs:element minOccurs="0" name="nearbyDistanceMeterClass" type="xs:string"/>
+                    
           <xs:choice maxOccurs="unbounded" minOccurs="0">
                         
             <xs:element name="constructionHeuristic" type="tns:constructionHeuristicPhaseConfig"/>
Error:  Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:355)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:253)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:884)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:844)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:450)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:299)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:963)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:296)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:199)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

```

**Comment by zepfred** [comment]
There is no need to open a separate PR to handle XSD changes.

**Pull request closed without merging**
